### ISSUE TITLE
Changer les parametres du blocage d'ip

### ISSUE THREAD

**Issue by yanisbinks** [PlanningBiblio/PlanningBiblio#1044]
Bonjour,

Est-il possible d'augmenter la tolérance aux mot de passes erronés ? 

Si oui pouvez-vous m'indiquer le paramètre à modifier ? 

Merci d'avance pour vos retours.

**Comment by jeromecombes** [comment]
Bonjour,

Oui, il s'agit des 3 paramètres commençant par "IPBlocker-" dans le menu "Administration / Configuration / Authentification".
La fonction de ces paramètres est expliquée en commentaire sur la page de configuration.

Cordialement,
Jérôme
