### ISSUE TITLE
Uncaught PHP Exception

### ISSUE THREAD

**Issue by Philall28** [PlanningBiblio/PlanningBiblio#1082]
Bonjour

Après mise à jour vers la version 24.10 j'ai le problème suivant dans la gestion des absences : 

"Uncaught PHP Exception Twig\Error\RuntimeError: "Key "deleted" for sequence/mapping with keys "perso_id, nom, prenom, sites, mail, mails_responsables, absence_id" does not exist." at edit.html.twig line 38"

Que ce soit avec des anciennes absences ou bien des nouvelles.

Merci d'avance
Cordialement
Philippe

**Comment by jeromecombes** [comment]
Bonjour Philippe,

C'est corrigé. Vous pouvez mettre à jour votre code en exécutant les commandes `git pull` et `composer install`

Notez que cette erreur n'apparaissait qu'avec le mode debug. Je vous invite à désactiver le mode debug en mettant APP_DEBUG=1 dans votre fichier .env.local

Cordialement,
Jérôme
