### ISSUE TITLE
Javascript inopérant dans l'ajout d'agent

### ISSUE THREAD

**Issue by Draky50110** [PlanningBiblio/PlanningBiblio#1087]
Bonjour.

Suite à la mise à jour en 24.10, si j'ajoute un agent, je fait de cliquer sur "Valider" ne donne rien (il ne se passe rien).
Si j'essaye d'attribuer des activités, les boutons ne donnent pas d'actions non plus.

**Comment by jeromecombes** [comment]
Bonjour,

Avez-vous bien exécuté "composer install" après avoir mis le code à jour ?
Si oui et si l'erreur persiste, videz le cache de votre navigateur.

Cordialement,
Jérôme

**Comment by Draky50110** [comment]
J'ai trouvé le souci.

Lorsque l'ont clique sur "Ajouter" ça doit charger modif.js mais ce JS n'est pas renseigné correctement dans la source.

Dans mon cas, il essaye d'appeler un fichier modif.js dans root/personnel/js/modif.js au lieu d'aller dans le chemin relatif root/planno/public/personnel/js/modif.js
J'ai copié ledit fichier où il l'attend mais je ne sais pas quel fichier source doit être corrigé.

Le bout de code fautif : 

<script type='text/JavaScript'>
              $(".select0").change(function(){calculHeures($(this),"","form","heures0",0);});
      $("document").ready(function(){calculHeures($(this),"","form","heures0",0);});
          $(".select1").change(function(){calculHeures($(this),"","form","heures1",1);});
      $("document").ready(function(){calculHeures($(this),"","form","heures1",1);});
      </script>
  <script src="[/personnel/js/modif.js](view-source:https://gilles.wittezaele.fr/personnel/js/modif.js)"></script>

**Comment by jeromecombes** [comment]
Merci pour ce retour.
C'est orrigé par le commit 4aeaefc86e03e542396c27343243f26261f74fa8
Ce sera intégré aux prochaines release (24.04.11 et 24.10.04)
