### ISSUE TITLE
Install procedure

### ISSUE THREAD

**Issue by mayweed** [PlanningBiblio/PlanningBiblio#169]
Hello
Did the install procedure change? I tried to go to planningBiblio via my url as indicated in the manual on the website but I cant get any install page. This is not my first install of planningBib though it's my first try in a docker. I've seen there has been huge and fondamental changes since BibLibre gets in , so do we need to use composer (and how?). Any hints would be (highly!) appreciated.
Thx

**Comment by jeromecombes** [comment]
Bonjour Guillaume,

Réponse rapide :

Procédure :

Version stable :

git clone https://github.com/planningbiblio/planningbiblio -b 19.10.xx
planningbiblio
cd planningbiblio
composer update

Pour obtenir composer : https://getcomposer.org/download

Nous n'avons pas encore testé en docker, retour d'expérience bienvenu.

Cdlt,
Jérôme



Le ven. 15 mai 2020 à 16:31, Guillaume R. <notifications@github.com> a
écrit :

**Comment by mayweed** [comment]
Salut Jérome
Voici l'erreur que j'ai après composer update: 
```
Executing script cache:clear [KO]
 [KO]
Script cache:clear returned with error code 1
!!  
!!  In FileLoader.php line 168:
!!                                                                                 
!!    Unable to read the "/var/www/planningBiblio/public/include/../../.env.local  
!!    " environment file in /var/www/planningBiblio/config/services.yaml (which i  
!!    s loaded in resource "/var/www/planningBiblio/config/services.yaml").        
!!                                                                                 
!!  
!!  In Dotenv.php line 51:
!!                                                                                 
!!    Unable to read the "/var/www/planningBiblio/public/include/../../.env.local  
!!    " environment file.                                                          
!!                                                                                 
!!  
!!  
Script @auto-scripts was called via post-update-cmd
```
Ce qui me semble bizarre vu les deux premières lignes de commentaire du fichier .env . Nevermind, j'ai cp .env en .env.local et je me suis gardé la page de doc de symphony sous le coude (https://symfony.com/doc/current/configuration.html ) pour lire et envisager les nouvelles possibilités de config . Mais je n'étais pas au bout de mes surprises puisque :
```
Executing script cache:clear [KO]
 [KO]
Script cache:clear returned with error code 255
!!  PHP Fatal error:  Uncaught Symfony\Component\Debug\Exception\UndefinedFunctionException: Attempted to call function "mysqli_connect" from the global namespace. in /var/www/planningBiblio/public/include/db.php:56
!!  Stack trace:
!!  #0 /var/www/planningBiblio/public/include/db.php(84): db->connect()
!!  #1 /var/www/planningBiblio/public/include/config.php(49): db->query('SELECT * FROM `...')
!!  #2 /var/www/planningBiblio/public/include/accessDenied.php(35): require_once('/var/www/planni...')
!!  #3 /var/www/planningBiblio/public/personnel/class.personnel.php(22): include_once('/var/www/planni...')
!!  #4 /var/www/planningBiblio/src/Controller/AgentController.php(13): require_once('/var/www/planni...')
!!  #5 /var/www/planningBiblio/vendor/symfony/debug/DebugClassLoader.php(155): include('/var/www/planni...')
!!  #6 [internal function]: Symfony\Component\Debug\DebugClassLoader->loadClass('App\\Controller\\...')
!!  #7 [internal function]: spl_autoload_call('App\\Controller\\...')
!!  #8 /var/www/planningBiblio/vendor/symfony/config/Resource/ClassExistenceResource.ph in /var/www/planningBiblio/public/include/db.php on line 56
!!  

```
Là je bloque, et je vais réfléchir, si tu as des suggestions, je suis preneur. 
Merci
Guillaume

**Comment by jeromecombes** [comment]
On peut ignorer les erreurs de script cache clear.
Elles se produisent lors de l'installation initiale. Ce script tente de se connecter à la base de données mais le lien n'est pas encore créé à cette étape.
Il est possible que composer install fonctionne sans erreur ici, mais sur la version 19.10, nous conseillons de lancer le composer update. Vous pouvez essayer composer install si votre version de PHP est 7.4 ou plus.

Actuellement, Planning Biblio n'est pas complètement sous symfony, on est en pleine migration et on va proposer pendant un certain temps une version hybride.
Donc on ne respecte pas à 100% les règles symfony et composer pour le moment.

NB : la procédure que j'ai donnée est pour l'installation de la version 19.10, logiquement celle-ci ne nous embête pas avec le .env.local

Pour installer la version master (non stable), il faut utiliser composer install au lieu de composer update
git clone https://github.com/planningbiblio/planningbiblio
cd planningbiblio
composer install
(on n'a pas de .env.local à cette étape. Si vous l'avez créé, supprimez-le)
on se connecte en HTTP(S), et on se laisse guider pour la suite (création du .env.local et de la base de données)

**Comment by mayweed** [comment]
Bonjour
Ca risque à mon grand désarroi d'être compliqué de sauter le pas avec cette version...Pourriez vous me dire quel est le dernier tag qui peut être utilisé en prod avant le passage en cours à Symfony svp? On va partir sur du stable en attendant que vous ayez terminé la migration vers quelque chose d'utilisable en prod.
Merci
Guillaume

**Comment by jeromecombes** [comment]
Le dernier tag stable (et sans symfony) est le [v19.10.05](https://github.com/PlanningBiblio/PlanningBiblio/releases/tag/v19.10.05) (voir onglet [Releases](https://github.com/PlanningBiblio/PlanningBiblio/releases)).
Vous pouvez également vous baser sur la branche [19.10.xx](https://github.com/PlanningBiblio/PlanningBiblio/tree/19.10.xx), comme expliqué dans ma première réponse. Ceci vous permettra de suivre les mises à jour mineures.

L’exécution de composer update reste nécessaire et une erreur peut apparaître au niveau de cache clear, mais elle ne sera pas bloquante (je viens de tester avec PHP 7.0 et je n'ai pas rencontré d'erreur)

`git clone https://github.com/planningbiblio/planningbiblio -b 19.10.xx`
`cd planningbiblio`
`composer update`

Cordialement,
Jérôme

**Comment by mayweed** [comment]
Salut Jérôme
Pour le coup ça passe, mais ça ne crée par la db, createdb.php affiche une page blanche (avec le logo planning bib) et rien ne se passe...Peut être au final que recréer  un fichier .env.local avec les bonnes données marcheraient? En créeant d'abord base de données et utilisateurs etc...Je ne pensais pas que c'était devenu aussi compliqué...
Merci pour ton aide
Guillaume

**Comment by mayweed** [comment]
Re @jeromecombes 
J'ai réussi à le passer dans un docker mais par contre pas à l'installer. J'ai toujours une page blanche :'(

Voici le dockerfile que j'ai utilisé:
```
#docker run -it -p8888:80 testpb3:latest /bin/bash
FROM debian:testing

#set hostname
RUN echo "SRVPLANNING" >> /etc/hostname

#general install
RUN apt-get update && \
apt-get upgrade -y && \
apt-get install -y \
apache2 \
default-mysql-server \
default-mysql-client \
php7.4 \
php7.4-curl \
php7.4-xml \
composer \
git \
apt-utils \
apt-transport-https \
ca-certificates \
vim \
wget \
unzip && \
apt-get clean

# -b 19.10.xx 
RUN mkdir -p /var/www/planningBiblio && \
git clone https://github.com/PlanningBiblio/PlanningBiblio/ /var/www/planningBiblio && \
chown -R www-data /var/www/planningBiblio && \
chgrp -R www-data /var/www/planningBiblio && \
chmod -R 755 /var/www/planningBiblio

RUN cd /var/www/planningBiblio && \
composer update  --no-scripts

COPY 000-default.conf /etc/apache2/sites-available/

EXPOSE 80
```
Sans le --no-scripts ça ne passe pas, j'ai pas eu le temps de tester d'autres trucs. J'étais un peu déçu de me retrouver devant une page blanche :'(
Guillaume

**Comment by jeromecombes** [comment]
Bonjour,

Pour la page blanche, consultez les logs apache. Vous y trouverez surement la réponse.

Pour le Docker file (simple lecture, sans avoir testé) : 
le mkdir n'est pas nécessaire, git créera le dossier
spécifiez bien la branche avec -b 19.10.xx, sinon la branche master sera utilisée, ce qui est déconseillé. De plus l'archi est différente et il faudra prendre en compte le dossier public dans la configuration Apache
Il ne faut pas faire un chown sur tout le dossier, le faire sur include et data est suffisant (pour les versions 19.10 et inférieures)
`chown -R www-data:www-data /var/www/planningBiblio/include`
`chown -R www-data:www-data /var/www/planningBiblio/data`
le chmod n'est pas nécessaire

Jérôme

**Comment by jeromecombes** [comment]
Bonjour Guillaume,

J'ai réussi à installer Planning Biblio avec votre Dockefile.

Vous devez ajouter les extensions PHP requises et notamment php7.4-mysqli
Voir toutes les extensions requises dans le fichier README.md (Calendar, mysqli, pdo, pdo-mysql)
(tests réalisés avec la branche 19.10.xx)

Cdlt,
Jérôme
