### ISSUE TITLE
Granularité heure demande de congés non respectée

### ISSUE THREAD

**Issue by cboonet** [PlanningBiblio/PlanningBiblio#210]
Bonjour,
Dans la version 20.04.04, il est impossible de saisir une demande de congés avec une granularité de 5 min (c'est seulement possible d'heure en heure) alors que la granularité est bien spécifiée à 5 minutes dans les options de configuration. 
Cela fonctionne en v19.10.05, cela semble donc être une régression.

Note : la granularité fonctionne bien pour les absences.

Cordialement,

![capture](https://user-images.githubusercontent.com/58264175/93059973-c8debf80-f671-11ea-9850-47a0b5825ff8.PNG)

**Comment by jeromecombes** [comment]
Bonjour,

Merci d'avoir déclaré ce souci.
Nous l'avons corrigé sur la PR #212 
Vous pouvez tester le correctif en exécutant les commandes suivantes : 
<pre>
git fetch origin
git checkout -b MT30038 origin/MT30038
</pre>

Merci par avance pour vos retours,
Jérôme

**Comment by cboonet** [comment]
Bonjour,
Merci.
J'ai testé le correctif, mais ça ne fonctionne toujours pas.

Les modifications du code source semblent bien présentes sur le serveur pourtant...

Cordialement,

**Comment by jeromecombes** [comment]
Bonjour,
Suite à l'application du correctif, il faut vider le cache côté serveur.
Pour ceci, placez-vous dans le dossier Planning Biblio et supprimez le sous dossier var/cache/dev (rm -r var/cache/dev ou sudo rm -r var/cache/dev)

**Comment by cboonet** [comment]
Bonjour,
Merci, c'était bien le cache.
Le problème est résolu.
Merci beaucoup
Cordialement,

**Comment by jeromecombes** [comment]
Merci pour le retour

**Comment by jeromecombes** [comment]
Le correctif sera prochainement intégré à la branche 20.04.xx,
Quand ce sera le cas, vous pourrez revenir sur cette branche en suivant cette procédure :
<pre>
git checkout 20.04.xx
git pull origin 20.04.xx
rm -r var/cache/dev
</pre>
