### ISSUE TITLE
Modification et supression d'absences impossibles

### ISSUE THREAD

**Issue by oliviercrouzet** [PlanningBiblio/PlanningBiblio#211]
Bonjour,
Sur la version 20.04.03, un agent, ne peut modifier ou supprimer ses propres absences, même si la permission est bien cochée dans son profil.
En fait la page d'édition de l'absence n'affiche pas les boutons Modifier et Supprimer.

Olivier Crouzet

**Comment by jeromecombes** [comment]
Bonjour,

Cette fonction n'est permise que si l'absence n'est pas validée (ni au niveau 1, ni au niveau 2).
Ceci nécessite également que le paramètre Absences-validation soit coché (sinon, les absences sont directement validées).

Je viens de tester et ça fonctionne bien chez moi.
Merci de vérifier ceci et me dire ce qu'il en est.

Cordialement,
Jérôme

**Comment by oliviercrouzet** [comment]
Ah OK, on n'avait pas vu ce détail trivial ! après avoir coché la bonne case, ça fonctionne bien aussi chez nous.
Merci pour ces précisions.

Olivier
