### ISSUE TITLE
BIS : Modification et supression d'absences impossibles #211

### ISSUE THREAD

**Issue by sbouis** [PlanningBiblio/PlanningBiblio#214]
Bonjour,
je vois que le ticket a été fermé mais il y a une mauvaise compréhension du problème.
Jusqu'à présent, en 19.04, nous n'avions pas de validation par les N+1 et les responsables planning des absences, ce qui est beaucoup trop lourd pour nous.. Le paramètre Absences-validation était bien décoché.
Cela n’empêchait pas les collègues qui avaient le droit de "Modifier ses propres absences" de modifier et supprimer leur absences. 
Est-ce que ce changement de comportement a été demandé par des usagers ?
Pour tout dire, c'est complétement bloquant pour notre fonctionnement actuel.

Est-ce qu'on pourrait envisager que la notion de validation de l'absence ne soit vérifiée pour autoriser modification et suppression que si  Absences-validation est coché mais pas quand Absences-validation est décoché ?

**Comment by jeromecombes** [comment]
Je viens de tester en 24.10 : 
Avec le paramètre Absences-validation décoché, un agent avec le droit "Modifier ses propres absences" peut modifier et supprimer ses absences.
