### ISSUE TITLE
Correction de la documentation - prérequis PHP

### ISSUE THREAD

**Issue by supertarto** [PlanningBiblio/PlanningBiblio#271]
Bonjour,

Je viens de tenter un upgrade en 20.10.xx depuis une 20.04.05.

Dans la documentation, en prérequis, il est précisié "PHP 7.0 ou supérieure (version 7.4 conseillée)". Sur mes serveurs, j'utilise principalement Debian et par défaut, PHP7.4 n'est pas disponible sur Debian10. J'ai donc tenté l'installation avec PHP7.3, mais ça a échoué car certaines dépendances Composer ne fonctionnent pas avec PHP7.3. (par exemple ocramius/proxy-manager en v2.8). 

Peut-être faudrait-il préciser que PHP7.4 est nécessaire et non conseillé en 20.10.xx?

En vous remerciant pour votre travail,
Cordialement,

**Comment by jeromecombes** [comment]
Bonjour,

Merci pour cette information.
Ce sera corrigé rapidement.

PR relatives : #272 #273 

Cordialement,
Jérôme
