### ISSUE TITLE
Access denied on workinghour index if no right 1101

### ISSUE THREAD

**Issue by alexarn** [PlanningBiblio/PlanningBiblio#316]
To reproduce:

 - Login with a user A
 - Set the following permissions for this user:
   - Managing working hours - validation level 1 (1101): unchecked
   - Managing working hours - validation level 2 (1201): checked
 - Go to working hours index page => Access denied

We should have acces to this page if we have at leave one of these 2 permissions (1101 or 1201).

**Comment by jeromecombes** [comment]
Corrigé depuis janvier 2021
