### ISSUE TITLE
Mise à jour des heures de présence avec pause dans l'onglet de la fiche agent

### ISSUE THREAD

**Issue by sbouis** [PlanningBiblio/PlanningBiblio#328]
Bonjour,
les heures de présence peuvent être gérées dans Administration -> Heures de présence.
Dans cette partie, on peut ajouter des "temps de pause", qui permettent de comptabiliser le réel volume horaire de l'agent si sa pause n'est pas fixe. 
Dans la partie Administration -> Agent, si on va sur l'onglet "Heures de présence", les valeurs saisies dans la partie "Administration -> Heures de présence." sont reprises mais sans décompter le temps de pause. On n'a donc des volumes horaires faux et non cohérents avec ce qui a été saisi par ailleurs.
Par exemple :
![image](https://user-images.githubusercontent.com/31436815/105982167-3b878f00-6097-11eb-98bc-5f53d839ba5e.png)
![image](https://user-images.githubusercontent.com/31436815/105982253-54904000-6097-11eb-824a-7e372b251d2c.png)

**Comment by jeromecombes** [comment]
Corrigé sur les versions maintenues (23.10 et supérieures)
