### ISSUE TITLE
Configuration LDAP-ID-Attribute - supannAliasLogin

### ISSUE THREAD

**Issue by j-kwan** [PlanningBiblio/PlanningBiblio#381]
Bonjour,

Étant en train d'installer une instance de PlanningBiblio (20.10), je viens de me rendre compte que la configuration via l'interface web pour la partie LDAP posait un petit problème.
Pour une raison qui m'échappe encore, le fait de spécifier les propriétés LDAP en camel-case ne permet pas de retourner les entrées des comptes ou les valeurs lors de la recherche via  `Import LDAP`.

Après avoir fait quelques test, je me suis rendu compte qu'en mettant `LDAP-ID-Attribute=uid` au lieu de `LDAP-ID-Attribute`=`supannAliasLogin`, je récupérais bien des entrées LDAP mais sans les matricules pour `LDAP-Matricule`=`supannEmpId`. 
De ce fait, j'ai effectué un autre test en mettant `LDAP-Matricule`=`supannempid` (sans majuscule donc), et je récupérais bien la valeur pour cette propriété.
J'ai alors refais le test en enregistrant avec `supannAliasLogin`, mais cette fois-ci en corrigeant la valeur en base de données pour n'utiliser que des minuscules. 

```sql
UPDATE
  config 
SET 
  valeur="supannaliaslogin"
WHERE 
  nom="LDAP-ID-Attribute";
```
La recherche lors d'un import me liste bien des comptes du LDAP.

Par contre, comme la page de configuration enregistre toutes les valeurs du formulaire, lorsque j'apporte une modification sur n'importe quel champ de cette page, la valeur de `LDAP-ID-Attribute` sera systématiquement modifié par rapport à une valeur de la liste.
Après avoir constaté que la liste des valeurs proposées pour `LDAP-ID-Attribute` se trouve dans la table `config` en base de données. La solution optée est donc de modifier directement les valeurs de la liste déroulante en base tout en remettant la valeur sélectionnée en minuscule.

```sql
-- Modification de supannAliasLogin pour éliminer les majuscules --
UPDATE
  config 
SET 
  valeur="supannaliaslogin",
  valeurs="uid,samaccountname,supannaliaslogin"
WHERE 
  nom="LDAP-ID-Attribute";
```

Il faudrait donc à terme que le champ `LDAP-ID-Attribute` de la page de configuration deviennent un champ texte, ou sinon que la propriété `supannAliasLogin` soit enregistrée en minuscule en base de données.

**Comment by jeromecombes** [comment]
Bonjour,

Merci pour ce retour.
Je viens de faire une Pull Request dans ce sens.

J'avais déjà passé samAccountName en minuscules pour les mêmes raisons.
Je viens de trouver quelques articles qui conseillent d'utiliser exclusivement des minucules.

Cordialement,
Jérôme

**Comment by j-kwan** [comment]
Super. Merci beaucoup !

Il y a aussi possibilité de faire un `strtolower()` avant insertion en base de données de tous les attributs LDAP.
Ceci permettrait de s'assurer que les recherches se feront toujours correctement quelle que soit la façon dont les usagers ont saisi le paramétrage.

Bien à vous,
