### ISSUE TITLE
Vérifier si un congés existe avant de le supprimer

### ISSUE THREAD

**Issue by sbouis** [PlanningBiblio/PlanningBiblio#394]
Bonjour,
Si une personne a ouvert un congés dans plusieurs onglet (ou dans plusieurs navigateurs) et qu'elle supprime ce congés une première fois mais le refait par erreur une deuxième fois dans l'autre onglet, le nombre d'heures de congés est réattribué deux fois à son contingent de congés.
Exemple :
![image](https://user-images.githubusercontent.com/31436815/111609024-2945e980-87da-11eb-8652-90ea20ed372d.png)

**Comment by jeromecombes** [comment]
Je reproduis sur 24.10 : à corriger

**Comment by jeromecombes** [comment]
Corrigé sur master (24.11.02), 24.04 (24.04.09) et 24.10 (24.10.02)
