### ISSUE TITLE
2 urls différentes pour l'import du calendrier ICS (dont une qui ne marche pas)

### ISSUE THREAD

**Issue by oliviercrouzet** [PlanningBiblio/PlanningBiblio#406]
Bonjour,

L'url qu'on trouve dans la partie administrateur (Administration / Les agents), onglet *Agendas et Synchronisation* est de ce type là :
`https://bu-planning.univ-lyon3.fr/agent/xx/ics/calendar.php?id=`

Celle qu'on trouve sur son compte de login (lien *Mon compte* en haut à droite) :
`https://bu-planning.univ-lyon3.fr//ics/calendar.php?id=`

La 1ère ne fonctionne pas.
La 2ème fonctionne. on remarque un double slash après l'adresse du serveur.

Olivier Crouzet

**Comment by jeromecombes** [comment]
Bonjour Olivier,

Nous allons vérifier et corriger ceci.

Merci,
Jérôme

**Comment by alexarn** [comment]
Ceci a été corrigé au mois de février. Je ferme cette issue.

https://github.com/PlanningBiblio/PlanningBiblio/pull/430
