### ISSUE TITLE
is cron.ics.php still working in v21.04.xx ?

### ISSUE THREAD

**Issue by jsicot** [PlanningBiblio/PlanningBiblio#434]
Hi,

is the cron script public/ics/cron.ics.php to import busy times from ics files still working on version 21.04.xx ?
I can't make it work on my end..
Thanks
Regards,
Julien

**Comment by jeromecombes** [comment]
Hi,

This script is still working, but you have to change the $path variable to point to the public folder.

Best,
Jérôme

**Comment by jsicot** [comment]
Dear Jerôme,
Thank you for reply
That's what I did, I saw that you had corrected this in one of the last posts. Thanks.

I have also another problem because the ics I tried to retrieve was behind a proxy, so I added HTTP context options to the initURL function in class.icsReader.php. Now, I wonder if this script supports ics with the [freebusy standard](https://www.kanzaki.com/docs/ical/freebusy.html) to manage absences by agent in Planningbiblio ?

when I run it, I get the following errors : 
```
PHP Notice:  Undefined variable: event in /path/to/planningbiblio/public/ics/ics-parser/class.iCalReader.php on line 433
PHP Notice:  Undefined index: VEVENT in /path/to/planningbiblio/public/ics/ics-parser/class.iCalReader.php on line 770
PHP Notice:  Undefined index: X-WR-CALNAME in /path/to/planningbiblio/public/ics/ics-parser/class.iCalReader.php on line 805
```
So i tested with a classic ics and it worked but my concern is is that this feature requires you to share your calendar publicly and make all your appointment information visible... it's a privacy issue, don't you think?
The freebusy ics would alleviate this as it would only make available information on busy/free slots without any other confidential or personal information.

Best,
Julien

**Comment by jeromecombes** [comment]
Bonjour Julien,

Le script d'importation se base sur les événements ICS complets et non sur les informations Free/Busy.
Je comprend ta demande de confidentialité mais les utilisateurs ayant demandé l'importation des événements voulaient importer l'ensemble (le titre de l'événement passse dans le champ "commentaires")

Pour une importation free/busy, il faudra demander un développement.

Depuis le début de cette conversation, le script d'importation a été déplacé dans le dossier src/Cron/Legacy. Il n'est plus nécessaire de l'adapter (plus de varible $path) et il ne faut plus le déplacer (comme conseillé auparavant).

Cordialement,
Jérôme
