### ISSUE TITLE
Erreur "maximum execution time of 30 seconds exceeded" sur l'exportation et visualisation des statistiques

### ISSUE THREAD

**Issue by msivapal** [PlanningBiblio/PlanningBiblio#50]
Erreur "maximum execution time of 30 seconds exceeded" sur l'exportation et visualisation des statistiques (par agent, par poste, par poste - synthèse, samedis) 
https://github.com/PlanningBiblio/PlanningBiblio/pull/56#issue-253650509
https://github.com/PlanningBiblio/PlanningBiblio/pull/55#issue-253568677
https://github.com/PlanningBiblio/PlanningBiblio/pull/53#issue-253563696
https://github.com/PlanningBiblio/PlanningBiblio/pull/52#issue-253561832

**Comment by jeromecombes** [comment]
Les statistiques ont été optimisées et il est à présent possible d'attribuer plus de mémoire à PHP depuis le fichier de configuration .env.local
