### ISSUE TITLE
Typo in cron.exportEDT.php

### ISSUE THREAD

**Issue by fridobox** [PlanningBiblio/PlanningBiblio#546]
https://github.com/PlanningBiblio/PlanningBiblio/blob/5bbc3bee4518f9ef578e6f17076f08913219caa8/public/planningHebdo/cron.exportEDT.php#L112

Looks like changes from "MT30755: Add more working hours cycles" introduced a typo in cron.exportEDT.php

Maybe its $d->semaine3 ?

**Comment by jeromecombes** [comment]
Right, thanks @fridobox 
@veggiematts, can you fix it ?

**Comment by jeromecombes** [comment]
Fixed !
