### ISSUE TITLE
Problème notifications après migration version 21.10

### ISSUE THREAD

**Issue by Gaston31** [PlanningBiblio/PlanningBiblio#549]
On vient de migrer de la version 2.7.16 à la dernière version (21.10.00) en suivant évidemment le guide (https://www.planningbiblio.fr/wp-content/uploads/2021/12/installation_21.10.pdf).
À présent, lorsqu’on valide un planning, la plupart des notifications ne partent pas, et les appels à disponibilité non plus !

**Comment by alexarn** [comment]
Bonjour,

L'erreur semble se produire lors de la validation d'un planning dont au moins un poste sans étage est occupé par un agent.
La proposition de correction est ici: https://github.com/PlanningBiblio/PlanningBiblio/pull/550

En attente de validation.

**Comment by Gaston31** [comment]
Bonjour
N'étant pas très familier avec le suivi de version via "github", je voidrais savoir si cela signifie que le dysfonctionnement va être "corrigé" ???

**Comment by alexarn** [comment]
> Bonjour N'étant pas très familier avec le suivi de version via "github", je voudrais savoir si cela signifie que le dysfonctionnement va être "corrigé" via la modification de la ligne 71 de "class.postes.php" décrite ici : [8b84105](https://github.com/PlanningBiblio/PlanningBiblio/commit/8b8410540941a6d094e2418ae71593f38c3ece06) Du coup, "git pull" ???

Vous pouvez tester en utilisant la branche MT35505:
```
git remote update
git checkout - b MT35505 origin/MT35505
php bin/console cache:clear
```
attention: dans ce cas vous serez sur la branche master (non stable)

Ou en appliquant le commit manuellement sur votre branche actuelle:
```
git remote udpate
git cherry-pick 8b8410540941a6d094e2418ae71593f38c3ece06
```

Dans tous les cas, lorsque la pull request sera validée, elle sera intégrée à la branche 21.10.xx et disponible sur la release 21.10.01

**Comment by Gaston31** [comment]
Le lancement de la commande "git remote udpate" provoque un message d'erreur ("Unknown subcommand") : peut-être version de "git" trop ancienne sur le système "CentOS" (v. 7) ?

Du coup, j'ai essayé de faire la modification "artisanalement" (édition du code), puis de redémarrer le service "Apache" : les messages d'erreur (PHP notice) "Undefined index" à l'exécution de la ligne 71 de "class.postes.php" ont disparu, mais les messages de notification ne partent pas beaucoup plus : quelques personnes et pour quelques plages les reçoivent, mais pas la majorité, et de loin !...

**Comment by Gaston31** [comment]
Edit: "L'appel à disponibilité" ne fonctionne plus non plus depuis la migration (doit utiliser les mêmes classes) !

**Comment by alexarn** [comment]
Bonjour,

Avez-vous des erreurs, warnings ou notices dans les logs de votre serveur web lors de la validation d'un planning ?

**Comment by Gaston31** [comment]
[:error] [pid 21798] [client :63719] [client ] ModSecurity: Warning. Operator GE matched 5 at TX:inbound_anomaly_score. [file "/etc/httpd/modsecurity.d/activated_rules/modsecurity_crs_60_correlation.conf"] [line "37"] [id "981204"] [msg "Inbound Anomaly Score Exceeded (Total Inbound Score: 34, SQLi=9, XSS=5): Possible XSS Attack Detected - HTML Tag Handler"] [hostname "planningbiblio-test.ut-capitole.fr"] [uri "/planning/poste/ajax.appelDispoMail.php"] [unique_id "YebEaxe0NyigTAIZQJvBcAAAAAA"], referer: /index.php?CSRFToken= page=planning%2Fposte%2Findex.php&site=1&tableau=137

**Comment by Gaston31** [comment]
Le problème est réglé pour les notifications lors de la validation des plannings : cela venait de restrictions concernant les envois massifs de courriels. Par contre, malgré la levée de ces restrictions, le problème persiste pour les notifications issues des "appels à disponibilité" : une idée ???

**Comment by jeromecombes** [comment]
Bonjour @Gaston31 ,

Pouvez-vous tester ce correctif : https://github.com/PlanningBiblio/PlanningBiblio/pull/556

Pour l'appliquer : 
- git remote update
- git checkout -b MT35523 origin/MT35523

Vider le cache de votre navigateur et tester.

Merci,
Jérôme

**Comment by Gaston31** [comment]
J'ai appliqué ces corrections "artisanalement" (version trop ancienne de "git" sur le serveur pour appliquer la commande "remote update"), et cela semble résoudre le problème.
