### ISSUE TITLE
Impossibilité créer absence récurrente (qqs heures)

### ISSUE THREAD

**Issue by Gaston31** [PlanningBiblio/PlanningBiblio#564]
Avec version 21.10, si on essaie de saisir une absence récurrente qui n’est pas la journée entière, on reçoit un message d’erreur « Accès refusé ».
Sur le même serveur, cela fonctionne toujours correctement avec la version 2.7.16…

**Comment by Gaston31** [comment]
Le problème ne se manifeste pas non plus avec la version 20.10

**Comment by jeromecombes** [comment]
Bonjour,

Ce problème a été identifié et corrigé. 
Le correctif est disponible sur la branche 21.10.xx
Pour en bénéficier, il suffit d'exécuter la commande "git pull"

Cordialement, 
Jérôme
