### ISSUE TITLE
erreur affichage granularité absences

### ISSUE THREAD

**Issue by supertarto** [PlanningBiblio/PlanningBiblio#581]
Bonjour,

Je viens de faire un upgrade en 21.10.00. Dans ma configuration, j'ai choisi une granularité au quart d'heure. Toutefois, quand je me rends dans le menu Absences, quand je veux choisir une heure de début ou de fin, les créneaux sont affichés par demi-heure. Que puis-je faire pour que mes créneaux soient affichés au quart d'heure?

**Comment by jeromecombes** [comment]
Bonjour,

Depuis la version 21.10, le pas affiché dans les menu est toujours à la demi-heure, mais les valeurs peuvent être adaptées au clavier en fonction de la granularité choisie en config.

Cordialement,
Jérôme

**Comment by supertarto** [comment]
Bonjour,

Je vous remercie pour cette réponse. Je ferais donc les manipulations nécessaires au clavier.
Bonne journée,
