### ISSUE TITLE
Les listes déroulantes heures n'affichent que les 1/2 h quelle que soit la granularité choisie

### ISSUE THREAD

**Issue by oliviercrouzet** [PlanningBiblio/PlanningBiblio#612]
Bonjour,
version 21.11
Quelque soit la granularité choisie dans la config (Divers/Granularité), les listes déroulantes heures dans les formulaires de dépôt des absences/conges/récupérations proposent un choix par 1/2 heure uniquement.
C'est lié à la fonction js suivante :
+++ b/public/js/plb/planno-timepicker.js
@@ -100,7 +100,7 @@ function formatHHmm(hour, minute) {

 function setTimePickerStep(granularity) {
   if (granularity == 1 || granularity == 15 || granularity == 5) {
     return 30;
   }
Est-ce que ça a un impact autre que sur l'affichage de ces listes si on modifie la valeur retournée (5 au lieu de 30 par exemple) ?

Olivier Crouzet

**Comment by jeromecombes** [comment]
Bonjour Olivier,

Dans les listes, les heures sont affichées avec un pas de 30 minutes, mais l'utilisateur peut affiner avec le clavier.
Ceci évite d'avoir des listes interminables.

Cdlt,
Jérôme
