### ISSUE TITLE
PHP Fatal error au lancement, index.php

### ISSUE THREAD

**Issue by mxlecanu** [PlanningBiblio/PlanningBiblio#687]
Bonjour à tous,

Je viens de procéder à la mise en place d'un serveur Ubuntu 22.04 LTS vierge, sur lequel j'ai installé les dernières versions de PHP (8.1.2), MariaDB (10.6.7) et Apache2 (2.4.52).
J'y ai installé Planno en version 22.04 sans erreur ou autre warning suspect.

Lors de l'accès à Planno, j'ai dans les log une "PHP Fatal error", et une erreur 500 dans mon navigateur :
"http_build_query() : Argument #1 ($data) must be of type array, null given in index.php on line 60"

La ligne en question est la suivante : 
        $login_params['redirURL'] = 'index.php?' . http_build_query($get);

Après avoir essayé de faire quelques manipulations par moi-même, j'ai contourné le problème en remplaçant toutes les références à la variable "$get" par "$_GET" et là ça fonctionne (mais je me doute que cette "bidouille" ne devrait pas être nécessaire).

A noter que je suis ingénieur logiciel (C, C++, Python, ...) mais je n'ai pas de recul en développement Web.
Je m'en remet donc aux experts pour essayer de m'éclairer sur la raison pour laquelle j'ai une erreur avec le code d'origine.

Je vous remercie par avance pour votre aide !

**Comment by anxest** [comment]
Bonjour,

Je retrouve la même erreur en php 8.0.21 + nginx sur Arch.

**Comment by alexarn** [comment]
Bonjour @mxlecanu,

Pouvez-vous partager vos modification ?

Alzex

**Comment by mxlecanu** [comment]
Mais comme expliqué dans mon précédent message, je ne saurais dire quel impact a cette modification, notamment en termes de sécurité.

**Comment by alexarn** [comment]
À priori je ne vois que la dépréciation de la constante FILTER_SANITIZE_STRING en PHP 8. Mais ce n'est qu'une dépréciation, ça n'explique pas l'erreur fatale.

Avez-vous pu tester le reste sous cette version ?

**Comment by mxlecanu** [comment]
Après avoir fait cette première modification vous voulez dire, oui j'ai effectivement pu tester le reste.

J'ai été confronté à un second problème sur la page "Agenda".
Le problème venait de la fonction @usort, qui dans le code d'origine utilise trois arguments alors que seuls deux sont autorisés dans la version de PHP que j'utilise.

Pour régler le problème, voici la modification que j'ai dû faire (src\PlanningBiblio\ClosingDay.php @ ligne77) :
`@usort($tab, "cmp_jour", true);`
remplacé par 
`@usort($tab, "cmp_jour");`

Un dernier soucis, pour lequel j'ai soumis une modification qui a été mergée au master récemment, concerne l'oubli d'une apostrophe (src\Controller\CalendarController.php @ ligne 100) :
`$db->select2("absences", null, "`perso_id`=$perso_id' $filter");`
remplacé par
`$db->select2("absences", null, "`perso_id`='$perso_id' $filter");`

Depuis ces dernières modifications, je n'ai plus de problème.

**Comment by jeromecombes** [comment]
Bonjour,

Merci pour vos retours d'expérience,

J'ajoute ici quelques notes qui seront à prendre en considération lors des adaptations à venir : 
* les filter_input sont nécessaires au maintien des règles de sécurité mais doivent être remplacés par l'utilisation des variables $request de Symfony. Voir sur quels fichiers ils sont conservés. Lorsque la migration vers Symfony sera achevée, il ne devrait pas en rester.
* De mémoire, le 3ème paramètre de la fonction usort est utilisé pour conserver les index d'origines dans les tableaux triés. Sans ce paramètre, les résultats risquent de ne pas être cohérents. Voir au cas par cas si ce paramètre doit être conservé ou non et s'il faudra trouver une solution de remplacement.

**Comment by jeromecombes** [comment]
Bonjour,

La Pull Request #697 corrige les erreurs mentionnées dans cette discussion.

**Comment by jeromecombes** [comment]
Les corrections ont été apportées sur les branches maintenues (master, 22.04.xx et 22.10.xx).
Ces 3 branches sont compatibles PHP 7.4, PHP 8.0 et PHP 8.1.
Des tests d'intégration continue sont en place pour tester ces 3 branches avec les 3 versions de PHP.
