### ISSUE TITLE
Debug symfony sur nginx

### ISSUE THREAD

**Issue by anxest** [PlanningBiblio/PlanningBiblio#698]
Bonjour,

Je n'arrive pas a utiliser planno depuis le passage à symfony (erreur 500 sur une majorité de pages, dans plusieurs versions de php). Ma configuration nginx ne me permet pas de visualiser le debogueur et je ne sais pas comment l'adapter. Est-ce qu'il serait possible de communiquer un modèle de configuration ?
Il y en avait un sur l'ancien site planningbiblio.fr, qui n'est plus accessible désormais (mais celui-ci datait peut etre d'avant la maj vers symfony).

**Comment by jeromecombes** [comment]
Bonjour,

Vous trouverez les exemples de configuration dans ce fichier :https://www.planno.fr/wp-content/uploads/2022/06/installation_21.10.pdf disponible sur https://www.planno.fr/installation/ (lien "Suivez le guide !")

Ce fichier parle de la version 21.10, mais les informations sont toujours d'actualité pour la version 22.04

Cordialement,
Jérôme

**Comment by anxest** [comment]
Ah pardon, cette version m'avait échappé. Malheureusement, cela n'active pas l'accès au débogueur symfony pour moi. Je vais donc continuer de creuser.

Par ailleurs, je retrouve également l'erreur signalée dans l'[issue 687](https://github.com/PlanningBiblio/PlanningBiblio/issues/687), malgré la mise à jour de la branche master : `PHP Fatal error:  Uncaught TypeError: http_build_query(): Argument #1 ($data) must be of type array, null given in /srv/http/planno/public/index.php:60`

**Comment by jeromecombes** [comment]
La correction mentionnée sur l'issue #687 n'est pas encore intégrée à master.
Pour tester Planno avec PHP8, utiliser la branche PHP8.1 tant que les corrections qui y sont apportées ne sont pas intégrées à master, 21.10.xx et 22.04.xx
Pour activer le débogueur Symfony, éditez votre fichier .env.local et modifiez la valeur de APP_ENV pour APP_ENV=dev
ceci activera la barre web_profiler sur la plupart des pages, et complétera les logs symfony que vous pouvez trouver dans le sous-dossier var/log de votre installation Planno.
Pour limiter les erreurs (surtout si vous utilisez PHP8), modifiez la valeur de APP_DEBUG dans ce même fichier pour APP_DEBUG=0

**Comment by anxest** [comment]
Merci pour ces précisions. En reprennant vos instructions, j'ai pu comprendre que l'erreur venait du micmac opéré par les changements de version de php. Je ne m'étais pas rendu compte qu'il fallait systématiquement refaire un composer install et un chmod -R sur le dossier var ensuite. L'appli semble fonctionner correctement désormais et je retrouve également la barre web_profiler.

Encore merci !
Et je confirme le bon fonctionnement en php8.1 sur la branche adéquate au passage.
