### ISSUE TITLE
Le Form de Changement de mot de passe ne s'affiche pas

### ISSUE THREAD

**Issue by anxest** [PlanningBiblio/PlanningBiblio#699]
La div#working_hours n'est pas fermée correctement. Cela provoque le positionnement de la div#motDePasse hors du conteneur div.ui-tabs et empêche l'affichage du formulaire par jquery.

Correction sur le fichier templates/myAccount.html.twig : remonter la ligne 69 en ligne 34

**Comment by jeromecombes** [comment]
@anxest Bonjour, 
Pouvez-vous préciser sur quelle branche vous constatez l'erreur ?
Merci

**Comment by anxest** [comment]
Bonjour, 

Je l'ai expérimenté en PHP8.1 mais j'observe le même fichier avec la ligne 34 incorrecte en master et en 22.04.xx (on voit une double indentation sur cette ligne, qui indique que la ligne qui se trouvait là a disparue et fait remonter le 2e Endif à sa place)

**Comment by anxest** [comment]
Corrigé en 22.04.xx. Merci bien
