### ISSUE TITLE
fix_encoding_issues : Unknown column '' in 'field list'

### ISSUE THREAD

**Issue by anxest** [PlanningBiblio/PlanningBiblio#701]
Bonjour,

Préparant la mise à jour d'une 19.10 vers une 22.04, j'ai voulu nettoyer la bdd des erreurs d'encodage avec les outils préparés, mais le script tools/fix_endoding_issues.php remontait plusieurs erreurs.

`PHP Fatal error:  Uncaught mysqli_sql_exception: Unknown column 'comand' in 'field list' in /srv/http/planno/public/include/db.php:89` 
Il s'agit simplement d'une faute de frappe, il sufft de rajouter le m manquant à "command" dans la table "cron".

`PHP Fatal error:  Uncaught mysqli_sql_exception: Unknown column '' in 'field list' in /srv/http/planno/public/include/db.php:89` 
Remonte pour chaque table listée pour laquelle aucune intervention n'est prévue, j'ai donc du les retirer (puisqu'il n'y a pas de colonnes a analyser dans ces tables, cela ne manque pas).

`PHP Fatal error:  Uncaught mysqli_sql_exception: Unknown column 'nom' in 'field list' in /srv/http/planno/public/include/db.php:89`
Remonte pour la table "pl_poste_modeles" car la colonne nom n'existe plus dans la version 22.04.

Je joins ma version modifiée (en txt pour le contrôle de github) : [fix_encoding_issues.txt](https://github.com/PlanningBiblio/PlanningBiblio/files/9356828/fix_encoding_issues.txt)

**Comment by alexarn** [comment]
PR #701 mergée sur master et 22.04.xx. Sera disponible en 22.04.01
