### ISSUE TITLE
Table 'planno.select_services' doesn't exist

### ISSUE THREAD

**Issue by anxest** [PlanningBiblio/PlanningBiblio#703]
Bonjour, 

Sur le fichier public/setup/maj.php, ligne 2636 et 2637, il manque un {$dbprefix} avant le nom des tables select_services et select_status, ce qui empêche la mise à jour dans le cas où un prefix est utilisé.

**Comment by alexarn** [comment]
Un correction est disponible. Voir la pull request #712 
Merci pour votre retour.

**Comment by alexarn** [comment]
La pull request est mergée sur les branches 22.04.xx et master.
Elle sera disponible pour les versions 22.04.01 et 22.05.00.001 (non stable)

**Comment by anxest** [comment]
Merci beaucoup
