### ISSUE TITLE
Table planning_hebdo_periodes doesn't exist

### ISSUE THREAD

**Issue by anxest** [PlanningBiblio/PlanningBiblio#716]
Bonjour,

En voulant vérifier si je pouvais cloturer les cas signalés précedemment, j'ai une nouvelle erreur en accedent à la page "Mon Compte".  Symfony me renvoit vers accountController.php et le log m'indique :

```[2022-09-03 09:45:59] request.CRITICAL: Uncaught PHP Exception mysqli_sql_exception: "Table 'empty_planno.planning_hebdo_periodes' doesn't exist" at /srv/http/empty-planno/public/include/db.php line 89 {"exception":"[object] (mysqli_sql_exception(code: 1146): Table 'empty_planno.planning_hebdo_periodes' doesn't exist at /srv/http/empty-planno/public/include/db.php:89)"} []
```

Sur la branche 22.04.xx à jour, nouvelle installation importée depuis le fichier `data/planningb_2110.sql.gz`. La table n'existe effectivement pas dans le fichier 2110, ni dans le fichier 1910.

Je dois commenter les lignes 37 à 40 de accountController.php pour contourner le problème.

**Comment by jeromecombes** [comment]
Bonjour,

C'est corrigé sur les branches maintenues (master, 22.04.xx et 22.10.xx) avec le commit "MT38918 : delete references to planning_hebdo_tables".

Cordialement,
Jérôme
