### ISSUE TITLE
export calendrier ics non fonctionnel

### ISSUE THREAD

**Issue by cboonet** [PlanningBiblio/PlanningBiblio#736]
Bonjour,
Sur notre version planningbiblio 21.04.02, depuis quelques temps (avant ça marchait), les utilisateurs ne peuvent plus importer leur calendrier en ics dans leur agenda perso.
L'ICS est bien généré (je récupère bien l'ics via l'url unique). Contenu de calendar.ics : 

> BEGIN:VCALENDAR
> X-WR-CALNAME:Service Public xxxxx X
> PRODID:Planning-Biblio-Calendar
> VERSION:2.0
> METHOD:PUBLISH
> BEGIN:VTIMEZONE
> TZID:Europe/Paris
> BEGIN:STANDARD
> DTSTART:16010101T030000
> TZOFFSETTO:+0100
> TZOFFSETFROM:+0200
> RRULE:FREQ=YEARLY;WKST=MO;INTERVAL=1;BYMONTH=10;BYDAY=-1SU
> TZNAME:CET
> END:STANDARD
> BEGIN:DAYLIGHT
> DTSTART:16010101T020000
> TZOFFSETTO:+0200
> TZOFFSETFROM:+0100
> RRULE:FREQ=YEARLY;WKST=MO;INTERVAL=1;BYMONTH=3;BYDAY=-1SU
> TZNAME:CEST
> END:DAYLIGHT
> END:VTIMEZONE
> END:VCALENDAR

Dans les logs apache, j'ai l'erreur suivante qui semble se produire au moment de la génération de l'ics : 
[Thu Sep 29 13:13:28.180192 2022] [php7:notice] [pid 7097] [client xxx.xxx.xxx.xxx:53582] PHP Notice:  Undefined index: entityManager in /var/www/html/planning/public/absences/class.absences.php on line 747
Est-ce un problème connu et résolu dans les nouvelles versions ? 
Avez-vous une solution pour régler ce problème dans notre version de planningbiblio ?

Merci pour votre retour.
Sébastien Leyreloup pour le SCDI de Montpellier

**Comment by alexarn** [comment]
Bonjour,

Je reproduis bien l'erreur en 21.04.02. Mais elle semble corrigée en 21.04.04
Pouvez-vous mettre à jour ?

Alex

**Comment by cboonet** [comment]
Bonjour,
Dans l'immédiat je ne peux pas mettre à jour l'application mais je vais le programmer avec les utilisateurs.
Je reviens vers vous dès que c'est fait.
Merci.

**Comment by cboonet** [comment]
Bonjour,
J'ai mis à jour l'application en 22.04 dans un environnement de test et l'export ics fonctionne bien.
Du coup on peut clore le ticket.
Merci.
