### ISSUE TITLE
Problème d'encodage dans une cellule "nom du poste"

### ISSUE THREAD

**Issue by oliviercrouzet** [PlanningBiblio/PlanningBiblio#758]
Sur cette cellule de classe _td_postes sticky-col_ (stockée dans le champ nom, table postes) au lieu de _Cadre d'astreinte_, nous avons :
Cadre d&#39;astreinte

**Comment by jeromecombes** [comment]
Les erreurs d'encodage des apostrophes ont été corrigées au niveau de l'affichage des tableaux (postes et noms des tableaux).
