### ISSUE TITLE
Planno 22.04 version : accès refusé à Jours de fermeture

### ISSUE THREAD

**Issue by patilloo** [PlanningBiblio/PlanningBiblio#818]
Bonjour,
depuis que nous avons installé la dernière mise à jour de Planno 22.04 postérieure au 10/11/2022, nous n'avons plus accès au menu Administration/Jours de fermeture (accès refusé) alors que la 22.04 installée en juin 2022 ne présentait pas ce bug.
Nous n'avons pas vérifié si la version 22.10 corrige ce bug.
Cordialement

**Comment by jeromecombes** [comment]
Bonjour,

Je viens de faire l'essai et je ne reproduis pas l'erreur.
Merci de vérifier que le processus de mise à jour complet a bien été suivi (notamment avec l'exécution de la commande `composer install`)
Vérifier que les droits d'accès au sous-dossier var de votre installation Planno sont corrects.
Merci de vérifier que le droit d'accès est coché dans votre fiche.
et de voir si une erreur liée apparaît dans vos journaux d'événements (log apache ou nginx, log symfony disponibles dans le sous-dossier var/log de votre installation Planno).

Cordialement,
Jérôme

**Comment by patilloo** [comment]
Bonjour,
pour info, nous avons fait les vérifications suggérées, pas d'anomalie trouvée mais le bug d'accès demeure.
L'accès est toujours refusé avec que la configuration et les droits d'accès sont bons.

**Comment by jeromecombes** [comment]
Pas d'anamalie constatée sur les versions récentes.
