### ISSUE TITLE
Erreur lors du lancement d'Apache

### ISSUE THREAD

**Issue by lefeuvrejerome** [PlanningBiblio/PlanningBiblio#820]
Avec Ubuntu 22.10 et PHP 8.1 , j'ai cette erreur dans /var/log/apache2/planningbiblio-error.log 

PHP Fatal error:  Declaration of Doctrine\\DBAL\\Driver\\PDOConnection::query() must be compatible with PDO::query(string $query, ?int $fetchMode = null, mixed ...$fetchModeArgs): PDOStatement|false in /var/www/planningbiblio/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php on line 86

Je pense qu'il faut modifier le code dans PDOConnection.php pour qu'il respecte le passage de parametre au driver PDOConnection ?

Quelqu'un à t'il une suggestion ? Merci

**Comment by jeromecombes** [comment]
Bonjour,

Quelle version de Planno utilisez-vous ?
Est-ce que l'erreur est constatée suite à une première installation ou suite à une mise à jour ?
Que ce soit une installation ou une mise à jour, avez-vous bien exécuté `composer install`  ?

**Comment by lefeuvrejerome** [comment]
Bonjour,

Merci pour votre promptitude.

J'utilise la dernière version de Planno, celle de git préconiser dans le guide d'installation

Erreur constaté suite à une première installation. Je précise Ubuntu 22.10 neuf également

J'ai bien exécute composer install.

Après quelque recherche , mais je suis pas assez pointu en code , je pense qu'il faut passer des paramètres en plus  ?

Cordialement

**Comment by jeromecombes** [comment]
Nous ne constatons pas cette erreur.
Dernière vérification, quelle version de composer utilisez-vous ?
Il faut la version 2 minimum

**Comment by lefeuvrejerome** [comment]
je pense que le résultat de la commande "composer  install " ci dessous peux vous parler . J'ai la dernière version de composer

Installing dependencies from lock file (including require-dev)
Verifying lock file contents can be installed on current platform.
Nothing to install, update or remove
Package doctrine/doctrine-cache-bundle is abandoned, you should avoid using it. No replacement was suggested.
Package sensio/framework-extra-bundle is abandoned, you should avoid using it. Use Symfony instead.
Package swiftmailer/swiftmailer is abandoned, you should avoid using it. Use symfony/mailer instead.
Package symfony/debug is abandoned, you should avoid using it. Use symfony/error-handler instead.
Package symfony/inflector is abandoned, you should avoid using it. Use EnglishInflector from the String component instead.
Package symfony/swiftmailer-bundle is abandoned, you should avoid using it. Use symfony/mailer instead.
Package php-cs-fixer/diff is abandoned, you should avoid using it. No replacement was suggested.
Generating autoload files
97 packages you are using are looking for funding.
Use the `composer fund` command to find out more!

Run composer recipes at any time to see the status of your Symfony recipes.

Executing script cache:clear [KO]
 [KO]
Script cache:clear returned with error code 1
!!  
!!  In CheckExceptionOnInvalidReferenceBehaviorPass.php line 31:
!!                                                                                 
!!    The service "doctrine.orm.default_entity_manager" has a dependency on a non  
!!    -existent service "doctrine.orm.naming_strategy.underscore_number_aware".    
!!                                                                                 
!!  
!!  
Script @auto-scripts was called via post-install-cmd

**Comment by jeromecombes** [comment]
Bonjour,

Pouvez-vous afficher les résultats des commandes suivantes : 
`git status`
`composer -V`

Merci,

**Comment by lefeuvrejerome** [comment]
Bonjour,


scd@planno:/var/www/planningbiblio$ git status
Sur la branche 21.10.xx
Votre branche est à jour avec 'origin/21.10.xx'.

Modifications qui ne seront pas validées :
  (utilisez "git add <fichier>..." pour mettre à jour ce qui sera validé)
  (utilisez "git restore <fichier>..." pour annuler les modifications dans le répertoire de travail)
	modifié :         .gitignore
	modifié :         composer.json
	modifié :         composer.lock
	modifié :         symfony.lock

aucune modification n'a été ajoutée à la validation (utilisez "git add" ou "git commit -a")

scd@planno:/var/www/planningbiblio$ composer -V
Composer version 2.4.4 2022-10-27 14:39:29

Merci

**Comment by jeromecombes** [comment]
Vous utilisez la branche 21.10.xx qui n'est plus maintenue.
Veuillez utiliser la branche 22.10.xx.

Merci,

**Comment by lefeuvrejerome** [comment]
C'est mieux en effet . J'avais bêtement suivi la doc 
https://www.planno.fr/wp-content/uploads/2022/06/installation_21.10.pdf

Cependant il doit me manquer des paquets car composer me retourne ceci , une idée ?
./composer.phar install
No composer.lock file present. Updating dependencies to latest instead of installing from lock file. See https://getcomposer.org/install for more information.
Loading composer repositories with package information
Updating dependencies
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Root composer.json requires php-webdriver/webdriver ^1.12 -> satisfiable by php-webdriver/webdriver[1.12.0, 1.12.1, 1.13.0, 1.13.1].
    - php-webdriver/webdriver[1.12.0, ..., 1.13.1] require ext-zip * -> it is missing from your system. Install or enable PHP's zip extension.
  Problem 2
    - Root composer.json requires dbrekelmans/bdi ^1.0 -> satisfiable by dbrekelmans/bdi[1.0].
    - dbrekelmans/bdi 1.0 requires ext-zip * -> it is missing from your system. Install or enable PHP's zip extension.
  Problem 3
    - symfony/panther[v1.1.0, ..., v1.1.2] require php-webdriver/webdriver ^1.8.2 -> satisfiable by php-webdriver/webdriver[1.12.0, 1.12.1, 1.13.0, 1.13.1].
    - php-webdriver/webdriver[1.12.0, ..., 1.13.1] require ext-zip * -> it is missing from your system. Install or enable PHP's zip extension.
    - Root composer.json requires symfony/panther ^1.1 -> satisfiable by symfony/panther[v1.1.0, v1.1.1, v1.1.2].

To enable extensions, verify that they are enabled in your .ini files:
    - /etc/php/8.1/cli/php.ini
    - /etc/php/8.1/cli/conf.d/10-mysqlnd.ini
    - /etc/php/8.1/cli/conf.d/10-opcache.ini
    - /etc/php/8.1/cli/conf.d/10-pdo.ini
    - /etc/php/8.1/cli/conf.d/15-xml.ini
    - /etc/php/8.1/cli/conf.d/20-calendar.ini
    - /etc/php/8.1/cli/conf.d/20-ctype.ini
    - /etc/php/8.1/cli/conf.d/20-curl.ini
    - /etc/php/8.1/cli/conf.d/20-dom.ini
    - /etc/php/8.1/cli/conf.d/20-exif.ini
    - /etc/php/8.1/cli/conf.d/20-ffi.ini
    - /etc/php/8.1/cli/conf.d/20-fileinfo.ini
    - /etc/php/8.1/cli/conf.d/20-ftp.ini
    - /etc/php/8.1/cli/conf.d/20-gettext.ini
    - /etc/php/8.1/cli/conf.d/20-iconv.ini
    - /etc/php/8.1/cli/conf.d/20-intl.ini
    - /etc/php/8.1/cli/conf.d/20-mbstring.ini
    - /etc/php/8.1/cli/conf.d/20-mysqli.ini
    - /etc/php/8.1/cli/conf.d/20-pdo_mysql.ini
    - /etc/php/8.1/cli/conf.d/20-phar.ini
    - /etc/php/8.1/cli/conf.d/20-posix.ini
    - /etc/php/8.1/cli/conf.d/20-readline.ini
    - /etc/php/8.1/cli/conf.d/20-shmop.ini
    - /etc/php/8.1/cli/conf.d/20-simplexml.ini
    - /etc/php/8.1/cli/conf.d/20-sockets.ini
    - /etc/php/8.1/cli/conf.d/20-sysvmsg.ini
    - /etc/php/8.1/cli/conf.d/20-sysvsem.ini
    - /etc/php/8.1/cli/conf.d/20-sysvshm.ini
    - /etc/php/8.1/cli/conf.d/20-tokenizer.ini
    - /etc/php/8.1/cli/conf.d/20-xmlreader.ini
    - /etc/php/8.1/cli/conf.d/20-xmlwriter.ini
    - /etc/php/8.1/cli/conf.d/20-xsl.ini
You can also run `php --ini` in a terminal to see which files are used by PHP in CLI mode.

**Comment by lefeuvrejerome** [comment]
J'ai résolu le problème en installant le package suivant , merci beaucoup
sudo apt-get install php-zip

**Comment by jeromecombes** [comment]
Je viens de mettre à jour le guide d'installation : https://www.planno.fr/wp-content/uploads/2022/12/installation_22.10.pdf

**Comment by lefeuvrejerome** [comment]
Super . Merci
