### ISSUE TITLE
ajax.updateCell.php ne fonctionne plus

### ISSUE THREAD

**Issue by tixif** [PlanningBiblio/PlanningBiblio#828]
Bonjour,

Dans la version 22.10.xx la copie d'un agent d'une heure à une autre (avec la flèche de droite) ne fonctionne plus.

Cela fonctionne bien avec la version 22.04, le problème semble être localisé ici : public/planning/poste/ajax.updateCell.php

seb

**Comment by tixif** [comment]
Ligne 125 :
`//if ($barrer == 0 and !$ajouter) {
    if (!$barrer and !$ajouter) {
`

Corrige le problème, mais en ajoute peut être d'autres... enfin, la fonctionnalité est rétablie avec ça

**Comment by jeromecombes** [comment]
Bonjour, j'ai proposé la correctif #828 qui sera revu, testé puis intégré par un développeur de BibLibre.
Votre correctif me semble correct également. J'ai fait quelques essais et le test modifié en ligne 125 fonctionne correctement.

**Comment by jeromecombes** [comment]
C'est corrigé sur la version 22.10.03
