### ISSUE TITLE
Bug statistiques

### ISSUE THREAD

**Issue by tixif** [PlanningBiblio/PlanningBiblio#831]
Bonjour,

Bug assez difficile à décrire, visible sur l'instance de démo : https://planno.demo.biblibre.eu/statistics/agent

"Paul Valery" fait une heure le 04/01/22. Si on affiche uniquement ses stats à lui sur ce jour, on a bien son heure.
Si on choisit d'afficher ses stats et celle d'au moins une personne **au dessus** dans la liste, son heure disparait... Si on choisit quelqu'un en dessous dans la liste, son heure est là...

![Firefox_Screenshot_2023-01-04T16-18-04 119Z](https://user-images.githubusercontent.com/17006660/210600534-c183fd31-cdc4-4ab4-85eb-4e44b5817c14.png)
![Firefox_Screenshot_2023-01-04T16-18-52 451Z](https://user-images.githubusercontent.com/17006660/210600654-c4d1555e-8ad3-49d5-ba31-5ed476c2ff31.png)
![Firefox_Screenshot_2023-01-04T16-19-16 518Z](https://user-images.githubusercontent.com/17006660/210600740-cd40f65b-30d3-4cb5-89ee-b900c3dd340b.png)

**Comment by jeromecombes** [comment]
Bonjour,

Cette erreur a été corrigée.

Cordialement,
Jérôme
