### ISSUE TITLE
Fallback on default theme doesn't work

### ISSUE THREAD

**Issue by alexarn** [PlanningBiblio/PlanningBiblio#84]
Having an empty or invalid value in Affichage-theme option make the configuration page theme broken instead of falling back on the default one.

Repoduce:
- Go to Administration > Configuration
- Empty the Affichage-theme option (in "Affichage" part) or set an invalid value ("foooo")
- Save => no more theming.

**Comment by jeromecombes** [comment]
Corrigé sur 20.04.xx et master
