### ISSUE TITLE
CAS-SQL connexion SQL hors Admin impossible

### ISSUE THREAD

**Issue by chaudebault** [PlanningBiblio/PlanningBiblio#850]
Bonjour,
En 22.10.03 il m'est impossible de me connecter à des comptes SQL à part le compte Admin.
Notre mode d'authentification est CAS-SQL, les utilisateurs du CAS n'ont aucun soucis.
Voici l'erreur remontée par Symfony en mode debug:
![image](https://user-images.githubusercontent.com/29449458/212267549-81d4d78c-941d-4612-8f22-c52bd9659b38.png)

Les log:
`Uncaught PHP Exception ErrorException: "Warning: Undefined variable $auth" at /var/www/planningbiblio/src/Controller/AuthorizationsController.php line 92

{
    "exception": {
        "xdebug_message": "<tr><th align='left' bgcolor='#f57900' colspan=\"5\"><span style='background-color: #cc0000; color: #fce94f; font-size: x-large;'>( ! )</span> ErrorException: Warning: Undefined variable $auth in /var/www/planningbiblio/src/Controller/AuthorizationsController.php on line <i>92</i></th></tr>\n<tr><th align='left' bgcolor='#e9b96e' colspan='5'>Call Stack</th></tr>\n<tr><th align='center' bgcolor='#eeeeec'>#</th><th align='left' bgcolor='#eeeeec'>Time</th><th align='left' bgcolor='#eeeeec'>Memory</th><th align='left' bgcolor='#eeeeec'>Function</th><th align='left' bgcolor='#eeeeec'>Location</th></tr>\n<tr><td bgcolor='#eeeeec' align='center'>1</td><td bgcolor='#eeeeec' align='center'>0.0003</td><td bgcolor='#eeeeec' align='right'>382176</td><td bgcolor='#eeeeec'>{main}(  )</td><td title='/var/www/planningbiblio/public/index_symfony.php' bgcolor='#eeeeec'>.../index_symfony.php<b>:</b>0</td></tr>\n<tr><td bgcolor='#eeeeec' align='center'>2</td><td bgcolor='#eeeeec' align='center'>0.0681</td><td bgcolor='#eeeeec' align='right'>1225312</td><td bgcolor='#eeeeec'>Symfony\\Component\\HttpKernel\\Kernel->handle( <span>$request = </span><span>class Symfony\\Component\\HttpFoundation\\Request { public $attributes = class Symfony\\Component\\HttpFoundation\\ParameterBag { protected $parameters = [...] }; public $request = class Symfony\\Component\\HttpFoundation\\ParameterBag { protected $parameters = [...] }; public $query = class Symfony\\Component\\HttpFoundation\\ParameterBag { protected $parameters = [...] }; public $server = class Symfony\\Component\\HttpFoundation\\ServerBag { protected $parameters = [...] }; public $files = class Symfony\\Component\\HttpFoundation\\FileBag { protected $parameters = [...] }; public $cookies = class Symfony\\Component\\HttpFoundation\\ParameterBag { protected $parameters = [...] }; public $headers = class Symfony\\Component\\HttpFoundation\\HeaderBag { protected $headers = [...]; protected $cacheControl = [...] }; protected $content = NULL; protected $languages = NULL; protected $charsets = NULL; protected $encodings = NULL; protected $acceptableContentTypes = NULL; protected $pathInfo = &#39;/login&#39;; protected $requestUri = &#39;/login&#39;; protected $baseUrl = &#39;&#39;; protected $basePath = NULL; protected $method = &#39;POST&#39;; protected $format = NULL; protected $session = class Symfony\\Component\\HttpFoundation\\Session\\Session { protected $storage = class Symfony\\Component\\HttpFoundation\\Session\\Storage\\NativeSessionStorage { ... }; private $flashName = &#39;flashes&#39;; private $attributeName = &#39;attributes&#39;; private $data = [...]; private $usageIndex = 1 }; protected $locale = NULL; protected $defaultLocale = &#39;en&#39;; private $preferredFormat = NULL; private $isHostValid = TRUE; private $isForwardedValid = TRUE }</span>, <span>$type = </span>???, <span>$catch = </span>??? )</td><td title='/var/www/planningbiblio/public/index_symfony.php' bgcolor='#eeeeec'>.../index_symfony.php<b>:</b>54</td></tr>\n<tr><td bgcolor='#eeeeec' align='center'>3</td><td bgcolor='#eeeeec' align='center'>0.0821</td><td bgcolor='#eeeeec' align='right'>1459144</td><td bgcolor='#eeeeec'>Symfony\\Component\\HttpKernel\\HttpKernel->handle( <span>$request = </span><span>class Symfony\\Component\\HttpFoundation\\Request { public $attributes = class Symfony\\Component\\HttpFoundation\\ParameterBag { protected $parameters = [...] }; public $request = class Symfony\\Component\\HttpFoundation\\ParameterBag { protected $parameters = [...] }; public $query = class Symfony\\Component\\HttpFoundation\\ParameterBag { protected $parameters = [...] }; public $server = class Symfony\\Component\\HttpFoundation\\ServerBag { protected $parameters = [...] }; public $files = class Symfony\\Component\\HttpFoundation\\FileBag { protected $parameters = [...] }; public $cookies = class Symfony\\Component\\HttpFoundation\\ParameterBag { protected $parameters = [...] }; public $headers = class Symfony\\Component\\HttpFoundation\\HeaderBag { protected $headers = [...]; protected $cacheControl = [...] }; protected $content = NULL; protected $languages = NULL; protected $charsets = NULL; protected $encodings = NULL; protected $acceptableContentTypes = NULL; protected $pathInfo = &#39;/login&#39;; protected $requestUri = &#39;/login&#39;; protected $baseUrl = &#39;&#39;; protected $basePath = NULL; protected $method = &#39;POST&#39;; protected $format = NULL; protected $session = class Symfony\\Component\\HttpFoundation\\Session\\Session { protected $storage = class Symfony\\Component\\HttpFoundation\\Session\\Storage\\NativeSessionStorage { ... }; private $flashName = &#39;flashes&#39;; private $attributeName = &#39;attributes&#39;; private $data = [...]; private $usageIndex = 1 }; protected $locale = NULL; protected $defaultLocale = &#39;en&#39;; private $preferredFormat = NULL; private $isHostValid = TRUE; private $isForwardedValid = TRUE }</span>, <span>$type = </span><span>1</span>, <span>$catch = </span><span>TRUE</span> )</td><td title='/var/www/planningbiblio/vendor/symfony/http-kernel/Kernel.php' bgcolor='#eeeeec'>.../Kernel.php<b>:</b>201</td></tr>\n<tr><td bgcolor='#eeeeec' align='center'>4</td><td bgcolor='#eeeeec' align='center'>0.0821</td><td bgcolor='#eeeeec' align='right'>1459936</td><td bgcolor='#eeeeec'>Symfony\\Component\\HttpKernel\\HttpKernel->handleRaw( <span>$request = </span><span>class Symfony\\Component\\HttpFoundation\\Request { public $attributes = class Symfony\\Component\\HttpFoundation\\ParameterBag { protected $parameters = [...] }; public $request = class Symfony\\Component\\HttpFoundation\\ParameterBag { protected $parameters = [...] }; public $query = class Symfony\\Component\\HttpFoundation\\ParameterBag { protected $parameters = [...] }; public $server = class Symfony\\Component\\HttpFoundation\\ServerBag { protected $parameters = [...] }; public $files = class Symfony\\Component\\HttpFoundation\\FileBag { protected $parameters = [...] }; public $cookies = class Symfony\\Component\\HttpFoundation\\ParameterBag { protected $parameters = [...] }; public $headers = class Symfony\\Component\\HttpFoundation\\HeaderBag { protected $headers = [...]; protected $cacheControl = [...] }; protected $content = NULL; protected $languages = NULL; protected $charsets = NULL; protected $encodings = NULL; protected $acceptableContentTypes = NULL; protected $pathInfo = &#39;/login&#39;; protected $requestUri = &#39;/login&#39;; protected $baseUrl = &#39;&#39;; protected $basePath = NULL; protected $method = &#39;POST&#39;; protected $format = NULL; protected $session = class Symfony\\Component\\HttpFoundation\\Session\\Session { protected $storage = class Symfony\\Component\\HttpFoundation\\Session\\Storage\\NativeSessionStorage { ... }; private $flashName = &#39;flashes&#39;; private $attributeName = &#39;attributes&#39;; private $data = [...]; private $usageIndex = 1 }; protected $locale = NULL; protected $defaultLocale = &#39;en&#39;; private $preferredFormat = NULL; private $isHostValid = TRUE; private $isForwardedValid = TRUE }</span>, <span>$type = </span><span>1</span> )</td><td title='/var/www/planningbiblio/vendor/symfony/http-kernel/HttpKernel.php' bgcolor='#eeeeec'>.../HttpKernel.php<b>:</b>81</td></tr>\n<tr><td bgcolor='#eeeeec' align='center'>5</td><td bgcolor='#eeeeec' align='center'>0.1016</td><td bgcolor='#eeeeec' align='right'>1836992</td><td bgcolor='#eeeeec'>App\\Controller\\AuthorizationsController->check_login( <span>$request = </span><span>class Symfony\\Component\\HttpFoundation\\Request { public $attributes = class Symfony\\Component\\HttpFoundation\\ParameterBag { protected $parameters = [...] }; public $request = class Symfony\\Component\\HttpFoundation\\ParameterBag { protected $parameters = [...] }; public $query = class Symfony\\Component\\HttpFoundation\\ParameterBag { protected $parameters = [...] }; public $server = class Symfony\\Component\\HttpFoundation\\ServerBag { protected $parameters = [...] }; public $files = class Symfony\\Component\\HttpFoundation\\FileBag { protected $parameters = [...] }; public $cookies = class Symfony\\Component\\HttpFoundation\\ParameterBag { protected $parameters = [...] }; public $headers = class Symfony\\Component\\HttpFoundation\\HeaderBag { protected $headers = [...]; protected $cacheControl = [...] }; protected $content = NULL; protected $languages = NULL; protected $charsets = NULL; protected $encodings = NULL; protected $acceptableContentTypes = NULL; protected $pathInfo = &#39;/login&#39;; protected $requestUri = &#39;/login&#39;; protected $baseUrl = &#39;&#39;; protected $basePath = NULL; protected $method = &#39;POST&#39;; protected $format = NULL; protected $session = class Symfony\\Component\\HttpFoundation\\Session\\Session { protected $storage = class Symfony\\Component\\HttpFoundation\\Session\\Storage\\NativeSessionStorage { ... }; private $flashName = &#39;flashes&#39;; private $attributeName = &#39;attributes&#39;; private $data = [...]; private $usageIndex = 1 }; protected $locale = NULL; protected $defaultLocale = &#39;en&#39;; private $preferredFormat = NULL; private $isHostValid = TRUE; private $isForwardedValid = TRUE }</span>, <span>$logger = </span><span>class Symfony\\Bridge\\Monolog\\Logger { protected $name = &#39;app&#39;; protected $handlers = [0 =&gt; class Monolog\\Handler\\StreamHandler { ... }, 1 =&gt; class Symfony\\Bridge\\Monolog\\Handler\\ConsoleHandler { ... }]; protected $processors = [0 =&gt; class Symfony\\Bridge\\Monolog\\Processor\\DebugProcessor { ... }]; protected $microsecondTimestamps = TRUE; protected $exceptionHandler = NULL }</span> )</td><td title='/var/www/planningbiblio/vendor/symfony/http-kernel/HttpKernel.php' bgcolor='#eeeeec'>.../HttpKernel.php<b>:</b>169</td></tr>\n<tr><td bgcolor='#eeeeec' align='center'>6</td><td bgcolor='#eeeeec' align='center'>0.1016</td><td bgcolor='#eeeeec' align='right'>1837248</td><td bgcolor='#eeeeec'>Symfony\\Component\\ErrorHandler\\ErrorHandler->handleError( <span>$type = </span><span>2</span>, <span>$message = </span><span>&#39;Undefined variable $auth&#39;</span>, <span>$file = </span><span>&#39;/var/www/planningbiblio/src/Controller/AuthorizationsController.php&#39;</span>, <span>$line = </span><span>92</span> )</td><td title='/var/www/planningbiblio/src/Controller/AuthorizationsController.php' bgcolor='#eeeeec'>.../AuthorizationsController.php<b>:</b>92</td></tr>\n"
    }
}`
Auriez-vous une idée de l'origine du bug?
Merci
Cordialement

**Comment by jeromecombes** [comment]
Bonjour,
L'erreur devrait disparaître si vous désactiver le mode débug.
Dans le fichier .env.local, mettait APP_DEBUG=0 à la place de APP_DEBUG=1, ou ajoutez simplement cette ligne si elle n'existe pas.
Cordialement,
Jérôme
