### ISSUE TITLE
Colonne nom vide dans listes congés et récupérations

### ISSUE THREAD

**Issue by chaudebault** [PlanningBiblio/PlanningBiblio#851]
Bonjour,
En 22.10.03 si un agent à un niveau de validation 2 uniquement la colonne "Nom" dans les listes de congés et récupérations sont vides.
Si on lui donne les droits niveau 1 (même sans niveau 2) les noms apparaissent.
Niveau 2 uniquement:
![image](https://user-images.githubusercontent.com/29449458/212271195-4e2e9ed3-3177-4f8b-bdc5-f1a9c9665624.png)
Niveau 1 uniquement:
![image](https://user-images.githubusercontent.com/29449458/212271602-616aaf4c-fec1-462d-91d9-28934a17eb5b.png)
Auriez-vous une idée de l'origine du bug?
Merci
Cordialement

**Comment by jeromecombes** [comment]
Bonjour,

Cette erreur a été corrigée.
Si vous la constatez toujours, mettez votre Planno à jour.

Cordialement,
Jérôme
