### ISSUE TITLE
Importation d'un modèle non fonctionnel

### ISSUE THREAD

**Issue by jp-morvan** [PlanningBiblio/PlanningBiblio#855]
Bonjour,
Lorsque j'essaye d'importer un modèle, cela ne fonctionne pas et j'ai l'erreur suivante dans les logs : 

`[Wed Jan 18 15:12:35.951846 2023] [php7:error] [pid 4426] [client 10.104.100.98:57054] PHP Fatal error:  Uncaught Doctrine\\DBAL\\Types\\ConversionException: Could not convert database value "a:2:{i:0;i:99;i:1;i:100;}" to Doctrine Type json in /var/www/html/planning-sante.villejuif.fr/vendor/doctrine/dbal/lib/Doctrine/DBAL/Types/ConversionException.php:36\nStack trace:\n#0 /var/www/html/planning-sante.villejuif.fr/vendor/doctrine/dbal/lib/Doctrine/DBAL/Types/JsonType.php(63): Doctrine\\DBAL\\Types\\ConversionException::conversionFailed()\n#1 /var/www/html/planning-sante.villejuif.fr/vendor/doctrine/orm/lib/Doctrine/ORM/Internal/Hydration/SimpleObjectHydrator.php(140): Doctrine\\DBAL\\Types\\JsonType->convertToPHPValue()\n#2 /var/www/html/planning-sante.villejuif.fr/vendor/doctrine/orm/lib/Doctrine/ORM/Internal/Hydration/SimpleObjectHydrator.php(63): Doctrine\\ORM\\Internal\\Hydration\\SimpleObjectHydrator->hydrateRowData()\n#3 /var/www/html/planning-sante.villejuif.fr/vendor/doctrine/orm/lib/Doctrine/ORM/Internal/Hydration/AbstractHydrator.php(268): Doctrine\\ORM\\Internal\\Hydration\\SimpleObjectHydrator->hydrateAllData()\n#4 /var/ww in /var/www/html/planning-sante.villejuif.fr/vendor/doctrine/dbal/lib/Doctrine/DBAL/Types/ConversionException.php on line 36, referer: https://planning-sante.villejuif.fr/index.php?page=planning/poste/importer.php&date=2023-03-15&site=1&menu=off
`

Merci par avance

**Comment by jp-morvan** [comment]
J'ai oublié de préciser : version mise à jour ce jour, nettoyage complet des composants

**Comment by jeromecombes** [comment]
Bonjour, 

Merci d'indiquer votre numéro de version et la branchr utilisée. 

Est-ce que l'installation ou la mise à jour s'est déroulée sans erreur en suivant le processus indiqué dans le guide correspondant à la version utilisée ?

L'erreur que vous mentionnez étant connue est corrigée sur les branches maintenues. 

Cordialement, 
Jérôme

**Comment by jp-morvan** [comment]
Bonjour,

Nous sommes en origin/22.04.xx

Je viens de voir que nous étions en composer 1 donc je viens de faire la montée de version.
Je ne me souviens pas si les précédentes mises à jour s'étaient bien passées.

J'ai donc fait : 
git pull
composer install
php public/index.php

Lors de l'import du modèle, j'ai désormais : 
`[Tue Jan 24 14:26:43.790120 2023] [php7:error] [pid 19563] [client 10.104.100.98:38836] PHP Fatal error:  Uncaught JsonException: Syntax error in /var/www/html/planning-sante.villejuif.fr/vendor/doctrine/dbal/src/Types/JsonType.php:60\nStack trace:\n#0 /var/www/html/planning-sante.villejuif.fr/vendor/doctrine/dbal/src/Types/JsonType.php(60): json_decode()\n#1 /var/www/html/planning-sante.villejuif.fr/vendor/doctrine/orm/lib/Doctrine/ORM/Internal/Hydration/SimpleObjectHydrator.php(140): Doctrine\\DBAL\\Types\\JsonType->convertToPHPValue()\n#2 /var/www/html/planning-sante.villejuif.fr/vendor/doctrine/orm/lib/Doctrine/ORM/Internal/Hydration/SimpleObjectHydrator.php(63): Doctrine\\ORM\\Internal\\Hydration\\SimpleObjectHydrator->hydrateRowData()\n#3 /var/www/html/planning-sante.villejuif.fr/vendor/doctrine/orm/lib/Doctrine/ORM/Internal/Hydration/AbstractHydrator.php(270): Doctrine\\ORM\\Internal\\Hydration\\SimpleObjectHydrator->hydrateAllData()\n#4 /var/www/html/planning-sante.villejuif.fr/vendor/doctrine/orm/lib/Doctrine/ORM/Persisters/Entity/BasicEntityPersister.php(920): Doctrine\\ORM\\Internal\\Hydration\\AbstractHydrator->hydrateAll in /var/www/html/planning-sante.villejuif.fr/vendor/doctrine/dbal/src/Types/ConversionException.php on line 39, referer: https://planning-sante.villejuif.fr/index.php?page=planning/poste/importer.php&date=2023-02-21&site=1&menu=off`

**Comment by jeromecombes** [comment]
Il est important de savoir si les dernières mises à jour se sont bien passées car chaque mise à jour est accompagnée d'une série de modifications dans la base de données. Si l'une d'entre elles échoue, les données peuvent être corrompues et les mises à jour suivantes ne les corrigent pas.
Si votre table personnel contient encore des données sous la forme "{i:0;i:99;i:1;i:100;}" dans les champs droits et postes, c'est que la conversion de ces données prévues par l'une des mises à jour n'a pas été effectuée.

**Comment by jp-morvan** [comment]
J'avais 1 entrée dans la table personnel qui était dans ce cas alors que toutes les autres non. J'ai édité l'agent et juste enregistré et c'est ok.
L'erreur a disparu.
Merci
