### ISSUE TITLE
Erreur Doctrine-Bundle lors la mise à jour

### ISSUE THREAD

**Issue by jp-morvan** [PlanningBiblio/PlanningBiblio#857]
Bonjour,

En faisant les mises à jour de mes instances hier, je suis tombé sur une erreur Doctrine-Bundle.

Je fais un git pull puis composer install et j'ai l'erreur suivante : 

Executing script cache:clear [KO]
 [KO]
Script cache:clear returned with error code 255
!!  
!!   // Clearing the cache for the prod environment with debug                      
!!   // false                                                                       
!!  
!!  09:01:32 CRITICAL  [php] Uncaught Error: Call to undefined method Doctrine\ORM\Configuration::setSchemaIgnoreClasses() ["exception" => Error { …}]
!!  
!!  In srcApp_KernelProdContainer.php line 429:
!!                                                                                 
!!    Attempted to call an undefined method named "setSchemaIgnoreClasses" of cla  
!!    ss "Doctrine\ORM\Configuration".                                             
!!                                                                                 
!!  
!!  cache:clear [--no-warmup] [--no-optional-warmers] [-h|--help] [-q|--quiet] [-v|vv|vvv|--verbose] [-V|--version] [--ansi] [--no-ansi] [-n|--no-interaction] [-e|--env ENV] [--no-debug] [--] <command>
!!  
!!  
Script @auto-scripts was called via post-update-cmd

[Plus lisible sur cette photo](https://cdn.villejuif.fr/images/debug/erreur-doctrine.png)

J'ai fouillé un peu et je me suis rendu compte que le problème vient de doctrine-bundle depuis la version 2.7.0.
J'ai réussi à me débrouiller en passant la version maximale en 2.6.4 et là c'est ok.

**Comment by jeromecombes** [comment]
Bonjour,

Merci de vérifier que tous les prérequis sont respectés, notamment composer qui doit être en version 2 minimum. 

Cordialement, 
Jérôme Combes

**Comment by jp-morvan** [comment]
Ce n'était pas le cas effectivement, c'est corrigé.
Désolé
