### ISSUE TITLE
Agents disponibles pas visibles dans le planning

### ISSUE THREAD

**Issue by a-lagrange** [PlanningBiblio/PlanningBiblio#858]
A l'issue de la mise à jour 22.05, nous avons observé que les agents disponibles sur leur dernière heure de travail étaient dans la liste des agents indisponibles dans Planno.
C’est le format de stockage des heures de présence qui pose problème : dans le champs temps de la table planning_hebdo, les heures sont stockées sous la forme [["09:00","","","17:00"]. Si on les enregistre sous la forme [["09:00:00","","","17:00:00"], cela résout le problème.

**Comment by jeromecombes** [comment]
Bonjour,

Vous êtes en version 22.05, ce qui signifie que vous utilisez une branche non stable et non maintenue.
Merci d'utiliser la branche 22.10.xx sur laquelle l'erreur mentionnée est corrigée. 

Cordialement, 
Jérôme
