### ISSUE TITLE
Conteneurisation - Planno

### ISSUE THREAD

**Issue by captain-muffin** [PlanningBiblio/PlanningBiblio#872]
Bonjour,

je me permets de vous écrire afin de savoir s'il était envisagé de mettre en place une version de Planno compatible avec le format de conteneurs Linux ? En effet, en l'état Planno n'est à mon sens pas installable sur un environnement conteneurisé tel que Docker voir Kubernetes.

Ma question ici est : est-ce qu'une version compatible à la conteneurisation Linux est envisagée ? 

Merci à vous.

**Comment by jeromecombes** [comment]
Bonjour,

Je ne maîtrise pas Docker et encore moins Kebernetes, mais je sais que certains utilisent Planno sous Docker.
Personnellement, je l'installe dans des conteneurs LXD.

Cordialement,
Jérôme

**Comment by captain-muffin** [comment]
Bonjour,

Merci pour ton retour rapide. En fait un exemple d'utilisation sous Docker serait suffisante car sous Kubernetes la logique d'installation serait similaire. 

La difficulté que je vois ici pour lancer l'applicatif sous Docker c'est que le script `install.sh` effectue à la fois l'initialisation d'une base de données et la configuration de l'applicatif. Est-ce qu'il y aurait des exemples d'utilisation sous Docker qui existerait quelque part ?

Merci

**Comment by jeromecombes** [comment]
Je n'ai pas d'exemple sous docker.
Il ne faut pas utiliser le script install.sh
Ce qu'il faut faire c'est charger les données dans le conteneur MariaDB (il y des dumps dans le dossier data)
Installer le reste dans le conteneur PHP (téléchargement des sources avec la commande git et installation des composants avec `composer install`
faire la config sur service web dans le conteneur nginx ou apache
et lier les conteneurs.

**Comment by captain-muffin** [comment]
Merci, je teste cela, si ça fonctionne je pourrai faire une Merge Request afin de proposer un Dockerfile.
