### ISSUE TITLE
Le module de purge, financé par plusieurs bu, est-il intégré par défaut dans les versions récentes de Planno ? Dans la 22.04 ? Dans la  22.10 ?

### ISSUE THREAD

**Issue by jmmermet** [PlanningBiblio/PlanningBiblio#878]
Bonjour,
je n'arrive pas à trouver l'info sur la doc ou sur le site, et à part en lançant la commande pour voir ce qui se passe (!), je ne vois pas comment connaître cette info : 

Le module de purge, financé par plusieurs bu, est-il intégré par défaut dans les versions récentes de Planno ? Dans la 22.04 ? Dans la  22.10 ?

Si ce n'est pas le cas, comment faut-il l'installer ? J'ai bien une procédure, datant de la livraison de la fonctionnalité, mais je crains qu'elle soit obsolète. 

Un grand merci d'avance pour votre réponse
Cordialement

**Comment by jeromecombes** [comment]
Bonjour,

La purge des données est intégrée depuis la version 22.04.00

Vous trouverez la procédure en tapant la commande suivante : `php bin/console PlanningBiblio:PurgeData --help`

Cordialement,
Jérôme
