### ISSUE TITLE
Statistiques par agents - tri par site non fonctionnel

### ISSUE THREAD

**Issue by supertarto** [PlanningBiblio/PlanningBiblio#885]
BOnjour,
En version 22.04.xx, lorsque nous voulions produire des statistiques par agents pour un site donné, nous sélectionnions "tous" dans la colonne "agents" puis le site concerné dans la colonne "sites". Nous obtenions alors un tableau de résultat contenant des lignes uniquement pour les agents du site concerné.

Depuis la version 22.10.xx, en procédant de manière identique, nous obtenons un tableau de résultat qui contient également les agents des autres sites, même si les colonnes Postes, samedi et Absences sont vides. 
Est-il possible de revenir au fonctionnement en vigeur dans la version 22.04?  Ca en l'état, le tableau des résultat est vite illisible et c'est très fastidieux de sélectionner manuellement à chaque fois les seuls agents du site qui nous intéresse.

**Comment by jeromecombes** [comment]
Bonjour,
J'ai corrigé ceci sur la pull request #970 
Vous pouvez la tester et nous faire part de vos résultats.

**Comment by jeromecombes** [comment]
Corrigé depuis décembre 2023 sur les version 23.04.xx et supérieures.
