### ISSUE TITLE
Erreur d'écriture de log lors de l'exécution du module de purge

### ISSUE THREAD

**Issue by jmmermet** [PlanningBiblio/PlanningBiblio#888]
Bonjour,

lors de l'exécution du module de purge : `php bin/console PlanningBiblio:PurgeData "2"`
j'obtiens une erreur : 
```
In StreamHandler.php line 115:

  The stream or file "var/log/dev.log" could not be
  opened in append mode: failed to open stream: Permission denied
```
Pour info : 
```
-bash-4.2$ ls -llha var/log/dev.log
-rw-r--r--. 1 apache www-sid 83M 10 mars  11:46 var/log/dev.log
```
Pour info, la purge s'est correctement déroulée et a bien effacé les données antérieures à l'année civile 2021 (le texte de `--help` n'est pas très clair sur le rôle du paramètre, mais on devine !)

Amicalement

**Comment by jeromecombes** [comment]
Bonjour,

C'est parce que, dans votre cas, le propriétaire du fichier est apache et que le script a été lancé depuis un autre compte.
Nous conseillons de modifier la configuration de PHP-FPM (si utilisé) ou Apache (si utilisé) pour faire en sorte que le propriétaire des fichiers générés par la navigation web soit le même que celui utilisé pour les opérations de maintenance (composer install et php bin/console ...).

Cordialement,
Jérôme
