### ISSUE TITLE
Affichage sur tablettes et samrtphone

### ISSUE THREAD

**Issue by iressouche** [PlanningBiblio/PlanningBiblio#89]
Lors de l'affichage de planningbiblio sur tablettes et smartphone, le menu "absences" est masqué par l'icone planninbiblio (ou l'icone de remplacement).

**Comment by jeromecombes** [comment]
Bonjour,

Ceci est corrigé sur les versions maintenues (23.10 et supérieures) avec l'utilisation du "hamburger menu".
