### ISSUE TITLE
Accès refusé pour Poser des congés/récupérations

### ISSUE THREAD

**Issue by oliviercrouzet** [PlanningBiblio/PlanningBiblio#927]
Dans certains cas (ce n'est pas systématique), on obtient une page "Accès refusé" lorsqu'on clique sur "Poser des congés" ou "Poser des récupérations". Il y une erreur critique signalée par la barre d'outils de Symfony :
`Uncaught PHP Exception Twig\Error\RuntimeError: "Variable "holifay_info" does not exist." at /var/www/plannotest/templates/conges/add.html.twig line 360`

C'est résolu en corrigeant l'erreur de frappe holifay_info => holiday_info

**Comment by jeromecombes** [comment]
Bonjour @oliviercrouzet , c'est corrigé sur le PR #919 et ce sera intégré sur les prochaines mises à jour (22.10.10 et 23.04.03)
