### ISSUE TITLE
Message Erreur 'Impossible d'afficher le menu des agents'

### ISSUE THREAD

**Issue by jide22** [PlanningBiblio/PlanningBiblio#944]
Après recherche dans les logs il s'avère que cela provient de la présence d'un tiret dans le nom de la base mariadb lors de la requete SQL : show table status from nombase like 'planning_hebdo';
serait-il possible d'entourer le nom de la base par des ` ?

**Comment by jeromecombes** [comment]
Bonjour,

Oui, c'est possible.
à faire sur les lignes suivantes : 
```
public/planningHebdo/class.planningHebdo.php:        $db->query("show table status from {$GLOBALS['config']['dbname']} like '{$GLOBALS['config']['dbprefix']}planning_hebdo';");
public/personnel/class.personnel.php:        $db->query("show table status from {$GLOBALS['config']['dbname']} like '{$GLOBALS['config']['dbprefix']}personnel';");
public/absences/class.absences.php:        $db->query("show table status from {$GLOBALS['config']['dbname']} like '{$GLOBALS['config']['dbprefix']}absences';");
```

**Comment by jeromecombes** [comment]
Bonjour,

C'est corrigé depuis février sur les versions 23.04.xx et supérieures.

Cordialement,
Jérôme
