### ISSUE TITLE
librairie requise pour CAS

### ISSUE THREAD

**Issue by oliviercrouzet** [PlanningBiblio/PlanningBiblio#95]
Bonjour,
Après installation, j'ai eu ce message là au démarrage de Planning Biblio 19.04 :
Fatal error: Uncaught Error: Class 'DOMDocument' not found in /var/www/.../vendor/apereo/phpcas/source/CAS/Client.php
 résolu par l'installation de  php7.0-xml.

Peut-être faudrait-il la rajouter dans la liste des extensions prérequises ?

**Comment by jeromecombes** [comment]
Bonjour,

le module XML a été ajouté à la liste des prérequis.

Cordialement,
Jérôme
