### ISSUE TITLE
Mauvaise valeur de moyenne par service dans les statistiques.

### ISSUE THREAD

**Issue by qlouis1** [PlanningBiblio/PlanningBiblio#953]
Bonjour !

Dans les statistiques par service, la valeur de moyenne hebdomadaire pour tous les sites est réaffichée pour chaque site individuellement.

Dans le service.html.twig (ligne 135) c'est le elem.hebdo qui est réutilisé.

Ca ne devrait pas plutôt être une moyenne calculée par site ?

Merci,

Quentin

**Comment by jeromecombes** [comment]
Bonjour,

C'est corrigé par la Pull Request #947 
Le correctif sera intégré sur les versions maintenues fin octobre.

Cordialement,
Jérôme

**Comment by qlouis1** [comment]
Merci beaucoup !
