### ISSUE TITLE
Heure erronée dans la liste des absences

### ISSUE THREAD

**Issue by supertarto** [PlanningBiblio/PlanningBiblio#960]
Bonjour,

Lors de l'enregistrement d'une absence, l'heure indiquée dans la colonne "Demande" de la liste des absences est inférieure de deux heures à l'heure "réelle". Par exemple, si j'enregistre une absence à 11h30, l'heure indiquée dans la colonne "Demande" sera 9h30.

Sur mon serveur, l'heure indiquée par le système est bien la bonne.

Comment puis-je corriger ce problème?

**Comment by jeromecombes** [comment]
Bonjour,

Vérifiez le paramètre "date.timezone" dans votre fichier php.ini
Mettez "Europe/Paris" puis redémarrer votre service web ou PHP FPM

Cordialement,
Jérôme

**Comment by supertarto** [comment]
Bonjour,
Merci pour votre retour, c'était ça en effet, je n'y avais pas pensé... Désolé.
Cordialement,
