### ISSUE TITLE
Problème d'export des statistiques

### ISSUE THREAD

**Issue by a-lagrange** [PlanningBiblio/PlanningBiblio#962]
Impossible d'exporter les statistiques, que ce soit en csv ou xls
Message d'erreur : Accès refusé, qu'on soit utilisateur avec des droits étendus ou admin
Je n'ai pas trouvé de paramètres dans la configuration qui permette de donner ces droits.

**Comment by jeromecombes** [comment]
Bonjour,

Il n'y a pas de droit spécifique associé aux exports. Les personne qui peuvent consulter les stats peuvent les exporter.
Pas de paramètre non plu.

Il peut s'agir d'un manque de configuration sur le serveur. Le dossier public/data de Planno doit être accessible en lecture-écriture par le service web.

S'il s'agit uniquement de la feuille de temps, ça peut être lié à l'erreur corrigée sur la Pull Request #931 
Ce correctif sera intégré à la prochaine mise à jour.

Cordialement,
Jérôme

**Comment by a-lagrange** [comment]
Il y avait bien un problème d'accès au dossier public/data.
Merci
