### ISSUE TITLE
Ajouter un Service de rattachement casse la liste

### ISSUE THREAD

**Issue by anxest** [PlanningBiblio/PlanningBiblio#99]
Bonjour,

Lorsque l'on ajoute un nouveau service de rattachement (pole administratif, pole public, etc) dans le profil d'un agent, l'enregistrement de ce nouveau service semble bien fonctionner, mais lorsque l'on veut afficher la liste pour appliquer ce service à l'agent, c'est désormais la liste des statuts qui apparait à la place des services. 
Dans la BD, c'est également la liste des statuts qui apparait dans la table select_services après la création du nouveau service.

Sinon, bravo et merci beaucoup pour le travail accompli jusque là :)

**Comment by jeromecombes** [comment]
Bonjour,

Sous quelle version avez-vous ce problème ?
Je viens de faire un essai mais je n'ai pas constaté le bug.

Merci,
Jérôme

**Comment by anxest** [comment]
Ah !

J'ai testé sur une 19.04.xx (`git clone`, `composer install`). Je viens juste de faire un `git fetch -p`, `composer install` et setup une nouvelle bdd vierge pour retester. Le problème est toujours là pour moi.

Lorsque j'ajoute un nouveau service pour un agent, la liste des services d'origine (Pole public, pole administratif, pole informatique, etc) est supprimée. Apparait désormais dans la liste les statuts (Garde de nuit, AB, BAS, etc) et le nouveau service que je viens de créer pour mon test. L'enregistrement d'un nouveau service fonctionne donc bien, mais la liste d'origine (dont beaucoup correspondaient à notre fonctionnement) a été remplacée.

La 2e machine est un windows avec un xamp, sauf que je ne sais plus maintenant que j'y pense si j'ai fait un composer install dessus, je vais vérifier. J'ai récupéré la 19.04.01 en zip depuis la page de téléchargement : https://www.planningbiblio.fr/telechargement/ et le problème se présentait de la même manière.

**Comment by anxest** [comment]
19.04.04 dans les deux cas, pardon.

**Comment by jeromecombes** [comment]
Bonjour,

C'est corrigé par ceci e867436a6eaf0981878fac1eea023a7dc4932ac8
Appliqué sur les branches master, 19.04.xx et 19.10.xx
